name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: master
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install NPM packages
      run: npm ci
      working-directory: ./frontend

    - name: Create .env.local
      run: |
        touch .env.local
        echo NEXT_PUBLIC_BE_URL=$NEXT_PUBLIC_BE_URL >> .env.local
        echo NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID >> .env.local
      env:
        NEXT_PUBLIC_BE_URL: ${{ secrets.NEXT_PUBLIC_BE_URL }}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
      working-directory: ./frontend
    
    - name: Build website
      run: npm run build
      working-directory: ./frontend

    - name: Upload backend files
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: build
        publish_dir: ./

    - name: Upload frontend build files
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: build
        keep_files: true
        destination_dir: frontend
        publish_dir: ./frontend/.next
